
---
- name: Install k3s on a single-node Linux server
  hosts: k3s_node
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
          - sudo
        state: present
        update_cache: yes

    - name: Download and install k3s (latest stable)
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s service to be active
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Copy kubeconfig for remote use
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/{{ ansible_user }}/k3s.yaml
        remote_src: yes
        owner: "{{ ansible_user }}"
        mode: 0644
